[package]
name = "solswap"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
pyth-sdk-solana = "0.7.0"
switchboard-v2 = "0.4.0"

[lib]
crate-type = ["cdylib", "lib"]
